import type { Metadata } from "next";
import { Noto_Sans_JP } from "next/font/google";
import "./globals.css";
import Header from "@/component/Header";
import { NextAuthProvider } from "./lib/next-auth/provider";
import { Suspense } from "react";
import LoadingSpinner from "./loading";

// フォント設定に "display" オプションを追加
const geistSans = Noto_Sans_JP({
  variable: "--font-geist-sans",
  subsets: ["latin"],
  display: "swap", // レンダリングのパフォーマンスを最適化
});

const geistMono = Noto_Sans_JP({
  variable: "--font-geist-mono",
  subsets: ["latin"],
  weight: ["400"],
  display: "swap", // こちらも同様に追加
});

export const metadata: Metadata = {
  title: "Book commerce",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="ja">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <NextAuthProvider>
          <Header />
          <Suspense fallback={<LoadingSpinner />}>{children}</Suspense>
        </NextAuthProvider>
      </body>
    </html>
  );
}
